ci: debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -192,6 +192,8 @@ jobs:
       - name: Run services
         run: docker compose up -d
 
+      - run: env | grep DATABASE_URL || echo "DATABASE_URL not found"
+
       - name: Migrate database
         run: bun db:migrate
 
